### ISSUE TITLE
does not work with  429651874f64f312d2a3d

### ISSUE THREAD

**Issue by Wikinaut** [marcelklehr/ep_infopanel#1]
does not work in develop 429651874f64f312d2a3d

no further details available.

I tried direct and via reverse proxy.
Server does not answer.

**Comment by marcelklehr** [comment]
Is there some server log available?

**Comment by marcelklehr** [comment]
Btw, apparently on http://beta.etherpad.org/ it works....

**Comment by marcelklehr** [comment]
This is probably due to Pita/etherpad-lite#1092, not?
